### ISSUE TITLE
NameBox and TextBox change styles

### ISSUE THREAD

**Issue by Dari04** [Dari04/Visual-Novel#37]
Modifcar la caja de diálogo y del nombre, modificar posición de la caja del nombre.

Referencia: https://drive.google.com/drive/u/0/folders/1rVb0w4PxcpZJpT1Ht0qk6RrGiM7uEmHH

![image](https://user-images.githubusercontent.com/16655702/91647164-2db4db80-ea1d-11ea-941c-5bc140f0ab50.png)

**Comment by Dari04** [comment]
Hi @MarinaEariel and @MariaCravioto,

It's done! 


![image](https://user-images.githubusercontent.com/16655702/91647174-4b824080-ea1d-11ea-900e-f76b501e5a52.png)

![image](https://user-images.githubusercontent.com/16655702/91647177-51782180-ea1d-11ea-951d-e85f8dcadb6a.png)

**Comment by MarinaEariel** [comment]
Parte de #21
